In [26]:
import os
import tensorflow as tf

# Igonre warnings and info messages
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
print("TensorFlow version: ", tf.__version__)

TensorFlow version:  2.4.1


In [19]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [20]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.42731333, -0.0946698 , -0.57091767, -0.08821145,  0.6782133 ,
         0.05887967, -0.52541125, -0.80508685, -0.00512313,  0.58911777]],
      dtype=float32)

In [21]:
tf.nn.softmax(predictions).numpy()

array([[0.14208792, 0.08430683, 0.05236378, 0.08485307, 0.18260877,
        0.09829886, 0.05480171, 0.04143168, 0.09220456, 0.16704287]],
      dtype=float32)

In [22]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train[:1], predictions).numpy()

2.319743

In [27]:
model.compile(
    optimizer='adam',
    loss=loss_fn,
    metrics=['accuracy']
)

model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0634 - accuracy: 0.9798
Epoch 2/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0549 - accuracy: 0.9814
Epoch 3/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0465 - accuracy: 0.9849
Epoch 4/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0442 - accuracy: 0.9858
Epoch 5/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0447 - accuracy: 0.9859


In [28]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 0s - loss: 0.0749 - accuracy: 0.9779


[0.07491341233253479, 0.9779000282287598]

## Add a softmax to the model

In [25]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

predictions = probability_model(x_train[:1]).numpy()
predictions

array([[2.1904609e-10, 6.1478652e-08, 1.3387498e-07, 6.4832933e-02,
        5.4912410e-18, 9.3516564e-01, 6.4562292e-12, 8.1058653e-07,
        1.4531049e-09, 3.9122082e-07]], dtype=float32)